"use client";

import React, { useEffect, useState } from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { fetchAnalytics } from '@/lib/api';
import ErrorMetrics from '@/components/ErrorMetrics';
import { Cpu, Target, Scaling, GitMerge } from 'lucide-react';

export default function TwinPage() {
  const [analytics, setAnalytics] = useState<any>(null);

  useEffect(() => {
    const load = async () => {
      const data = await fetchAnalytics();
      setAnalytics(data);
    };
    load();
    const interval = setInterval(load, 2000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="flex flex-col gap-6 max-w-[1600px] mx-auto">
      <h1 className="text-2xl font-tech font-bold flex items-center gap-2">
        <Cpu className="text-primary" /> Digital Twin Engine
      </h1>

      <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-[10px]">Physics Node Status</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold font-mono text-emerald-500">ONLINE</div>
            <p className="text-xs text-muted-foreground mt-1">Euler integrations synced</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-[10px]">ML Predictor Node</CardTitle>
          </CardHeader>
          <CardContent>
             <div className="text-2xl font-bold font-mono">ACTIVE</div>
             <p className="text-xs text-muted-foreground mt-1">Isolation Forest Tracking</p>
          </CardContent>
        </Card>

        <Card className="xl:col-span-2">
          <CardHeader className="pb-2">
             <CardTitle className="text-[10px]">Current Threat Evaluation</CardTitle>
          </CardHeader>
          <CardContent className="flex items-center justify-between">
              <div>
                <div className="text-2xl font-bold font-mono text-danger">
                  {analytics?.anomaly_score ? (analytics.anomaly_score * 100).toFixed(1) : "0.0"}%
                </div>
                <p className="text-xs text-muted-foreground mt-1">Anomaly Probability</p>
              </div>
              <Badge variant={analytics?.anomaly ? "danger" : "success"} size="lg">
                 {analytics?.anomaly ? "SYSTEM ANOMALY" : "NOMINAL"}
              </Badge>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="min-h-[400px]">
          <CardHeader>
             <CardTitle className="flex items-center gap-2">
                <Target size={18} className="text-accent" />
                Physical vs Digital Variance
             </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col items-center justify-center py-10">
              <div className="w-full max-w-md">
                 <ErrorMetrics posError={analytics?.position_error || 0} tempError={analytics?.temperature_error || 0} />
              </div>
              <p className="text-center text-sm text-muted-foreground mt-8 max-w-md">
                  This metric represents the absolute drift between mathematical predictions generated by the physics engine and the real-world sensor streams.
              </p>
          </CardContent>
        </Card>

        <Card className="min-h-[400px]">
          <CardHeader>
             <CardTitle className="flex items-center gap-2">
                <GitMerge size={18} className="text-primary" />
                Latest Orchestrator Recommendation
             </CardTitle>
          </CardHeader>
          <CardContent className="flex items-center justify-center bg-muted/5 rounded-lg m-4 border border-border/50">
             {analytics?.recommendation ? (
                 <div className="p-8 text-center">
                    <p className="text-lg font-mono text-foreground/90">{analytics.recommendation}</p>
                    {analytics.issue_detected && (
                      <p className="text-sm font-bold text-danger mt-4 uppercase tracking-widest">
                         Requires Immediate Review
                      </p>
                    )}
                 </div>
             ) : (
                 <div className="text-muted-foreground font-mono text-sm">Waiting for recommendation...</div>
             )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
